ci(release): fail workflow as a reminder to generate release notes

diff --git a/.github/workflows/docker-release.yml b/.github/workflows/docker-release.yml
--- a/.github/workflows/docker-release.yml
+++ b/.github/workflows/docker-release.yml
@@ -74,3 +74,13 @@ jobs:
             images+=("${tag}@${DIGEST}")
           done
           cosign sign --recursive --yes "${images[@]}"
+      - name: Manually generate release note
+        shell: bash
+        run: |
+          set -euo pipefail
+          IFS=$'\n\t'
+          echo "This failure is expected. It is a reminder to update the release notes for this newly created release."
+          echo "To do so, go to ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/latest and click on the edit button."
+          echo "Then click on the 'Generate release notes' button and uncheck the 'Set as the latest release' box."
+          echo "Finally click the 'Update release' button. Cheers!"
+          exit 1
